name: Deploy to ftp

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      - name: Update baseurl and add version
        run: |
          TAG_NAME="${{ github.ref_name }}"
          TAG_MESSAGE=$(git tag -l --format='%(contents)' "$TAG_NAME")
          sed -i "s|baseurl: \"/fools\"|baseurl: \"/fools/$TAG_NAME\"|" _config.yml
          echo "" >> _config.yml
          echo "version: \"$TAG_NAME\"" >> _config.yml
          echo "version_message: |" >> _config.yml
          echo "  $TAG_MESSAGE" >> _config.yml
      - name: Create version data file
        run: |
          TAG_NAME="${{ github.ref_name }}"
          TAG_MESSAGE=$(git tag -l --format='%(contents)' "$TAG_NAME")
          mkdir -p _data
          jq -n \
            --arg tag "$TAG_NAME" \
            --arg message "$TAG_MESSAGE" \
            '{version: $tag, message: $message}' > _data/version.json
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Create metadata file
        run: |
          TAG_NAME="${{ github.ref_name }}"
          TAG_MESSAGE=$(git tag -l --format='%(contents)' "$TAG_NAME")
          TAG_TIME=$(git log -1 --format=%cI "$TAG_NAME")
          jq -n \
            --arg tag "$TAG_NAME" \
            --arg message "$TAG_MESSAGE" \
            --arg time "$TAG_TIME" \
            '{tag: $tag, message: $message, time: $time}' > ./_site/metadata.json
      - name: Upload via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./_site"
          remote_dir: "./${{ github.ref_name }}/" 